# -*- coding: utf-8 -*-
"""Assignment-1 Practical-3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14ApRWOaCNEXJLPVsuUwfBENINg34reA_
"""

#Practical-3 
#Take two numbers from user (input()). 
#write both numbers in a file called Input.txt.
#Read both number form file Input.txt and 
#Write answer of +, -, *, /, //, ** operations in file Output.txt

#opening file in write mode and taking inputs
file1 = open("Input.txt","w")
oprd1 = int(input("Enter first operand:"))
oprd2 = int(input("Enter second operand:"))

file1.write(str(oprd1)+"\n")
file1.write(str(oprd2))
#Closing Input file
file1.close()
#Opening Input and Output file in "r" and "w" mode respectively
file1 = open("Input.txt","r")
file2 = open("Output.txt","w")
#reading values from Input.txt
opr1 = int(file1.readline())
opr2 = int(file1.readline())

#Writing in the file
file2.write('Addition of %d and %d is:%d\n'%(opr1,opr2,(opr1+opr2)))
file2.write('Subtraction of %d and %d is:%d\n'%(opr1,opr2,(opr1-opr2)))
file2.write('Multiplication of %d and %d is:%d\n'%(opr1,opr2,(opr1*opr2)))
file2.write('Floarting point division of %d and %d is:%d\n'%(opr1,opr2,(opr1/opr2)))
file2.write('Integer point division of %d and %d is:%d\n'%(opr1,opr2,(opr1//opr2)))
file2.write('%d raised to %d is:%d\n'%(opr1,opr2,(opr1**opr2)))

#Closing the file
file1.close()
file2.close()