# -*- coding: utf-8 -*-
"""Assignment-1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10YGnX6AsYIejUZYfatyb1EWADQhWtEzT
"""

#Practical-1: 
#There are two Input files are available to you named Input1.txt and Input2.txt.
#Read content from both files write in file Output.txt

#Writing values in file
file1 = open("Input1.txt","w")
file2 = open("Input2.txt","w")
file1.write("ABCD\nEDG\nF\nRT\n")
file2.write("PQR\nXYZ\n")
#Closing Files
file1.close()
file2.close()

#Opening output file ain apprnd mode and Input1 and Input2 in read mode
file3 = open("Output.txt","a")
file1 = open("Input1.txt","r")
file2 = open("Input2.txt","r")
#copying data from Input1 and Input2
f1_output = file1.read()
f2_output = file2.read()
#Writing data in Output
file3.write(f1_output)
file3.write(f2_output)
#Closing all files
file1.close()
file2.close()
file3.close()

#Practical-2:
#There are two Input files are available to you named Input1.txt and Input2.txt.
#There are 5 numbers written in each file
#Read content from both files, perform addition on numbers
#And write it in file name Output.txt

#Oening files for writing content in it
file1 = open("Input1.txt","w")
file2 = open("Input2.txt","w")
file1.write("12\n13\n14\n15\n16\n")
file2.write("220\n23\n02\n25\n260")
#Closing files
file1.close()
file2.close()

#Opening Output file in "a" mode and Input1 and Input2 in "r" mode
file3 = open("Output.txt","w")
file1 = open("Input1.txt","r")
file2 = open("Input2.txt","r")

#performing addition of 5 data of both the fiel and writig back in Output file
f1_output = int(file1.readline())
f2_output = int(file2.readline())
file3.write(str(f1_output + f2_output))
file3.write("\n")

f1_output = int(file1.readline())
f2_output = int(file2.readline())
file3.write(str(f1_output + f2_output))
file3.write("\n")

f1_output = int(file1.readline())
f2_output = int(file2.readline())
file3.write(str(f1_output + f2_output))
file3.write("\n")

f1_output = int(file1.readline())
f2_output = int(file2.readline())
file3.write(str(f1_output + f2_output))
file3.write("\n")

f1_output = int(file1.readline())
f2_output = int(file2.readline())
file3.write(str(f1_output + f2_output))
file3.write("\n")

#Closing Files
file1.close()
file2.close()
file3.close()

#Practical-3 
#Take two numbers from user (input()). 
#write both numbers in a file called Input.txt.
#Read both number form file Input.txt and 
#Write answer of +, -, *, /, //, ** operations in file Output.txt

#opening file in write mode and taking inputs
file1 = open("Input.txt","w")
oprd1 = int(input("Enter first operand:"))
oprd2 = int(input("Enter second operand:"))

file1.write(str(oprd1)+"\n")
file1.write(str(oprd2))
#Closing Input file
file1.close()
#Opening Input and Output file in "r" and "w" mode respectively
file1 = open("Input.txt","r")
file2 = open("Output.txt","w")
#reading values from Input.txt
opr1 = int(file1.readline())
opr2 = int(file1.readline())

#Writing in the file
file2.write('Addition of %d and %d is:%d\n'%(opr1,opr2,(opr1+opr2)))
file2.write('Subtraction of %d and %d is:%d\n'%(opr1,opr2,(opr1-opr2)))
file2.write('Multiplication of %d and %d is:%d\n'%(opr1,opr2,(opr1*opr2)))
file2.write('Floarting point division of %d and %d is:%d\n'%(opr1,opr2,(opr1/opr2)))
file2.write('Integer point division of %d and %d is:%d\n'%(opr1,opr2,(opr1//opr2)))
file2.write('%d raised to %d is:%d\n'%(opr1,opr2,(opr1**opr2)))

#Closing the file
file1.close()
file2.close()

#Practical-4:
#Create Input.txt manually write 3 float numbers in it.
#The first number is a radius, second is the width and last is the height
#Read all number form file Input.txt and 
#calculate the following 
#1) Area of Circle
#2) Area of Rectangle
#3) Perimeter of Circle
#4) Perimeter of Rectangle
#Write all answers in file Output.txt

#Opening file Input.txt in "w" mode
file1 = open("Input.txt","w")
file1.write(str(12.6)+"\n")
file1.write(str(25.9)+"\n")
file1.write(str(15.33)+"\n")
file1.close()

#opening Input.txt and output.txt in "r" and "w" mode respectively
file1 = open("Input.txt","r")
file2 = open("Output.txt","w")
radius = float(file1.readline())
length = float(file1.readline())
breadth = float(file1.readline())
#Calculating area and perimeter of Circle and Rectangle
area_circle = 3.14*radius*radius
area_rectangle = length*breadth
peri_circle = 2*3.14*radius
peri_rectangle = 2*(length+breadth)
#Writing data into file
file2.write("Area of circle is:"+str(area_circle)+"\n")
file2.write("Area of rectangle is:"+str(area_rectangle)+"\n")
file2.write("Perimeter of circle is:"+str(peri_circle)+"\n")
file2.write("Perimeter of rectangle is:"+str(peri_rectangle)+"\n")
#closing the files
file1.close()
file2.close()