# -*- coding: utf-8 -*-
"""Assignemnt-1, Practical-2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oU-MYytUrNYiT8a6cXhw5icp839BqafL
"""

#Practical-2:There are two Input files are available to you named Input1.txt and Input2.txt.
#There are 5 numbers written in each file
#Read content from both files, perform addition on numbers
#And write it in file name Output.txt

#Oening files for writing content in it
file1 = open("Input1.txt","w")
file2 = open("Input2.txt","w")
file1.write("12\n13\n14\n15\n16\n")
file2.write("220\n23\n02\n25\n260")
#Closing files
file1.close()
file2.close()

#Opening Output file in "a" mode and Input1 and Input2 in "r" mode
file3 = open("Output.txt","w")
file1 = open("Input1.txt","r")
file2 = open("Input2.txt","r")

#performing addition of 5 data of both the fiel and writig back in Output file
f1_output = int(file1.readline())
f2_output = int(file2.readline())
f3_output = f1_output + f2_output
file3.write(str(f3_output))
file3.write("\n")

f1_output = int(file1.readline())
f2_output = int(file2.readline())
f3_output = f1_output + f2_output
file3.write(str(f3_output))
file3.write("\n")

f1_output = int(file1.readline())
f2_output = int(file2.readline())
f3_output = f1_output + f2_output
file3.write(str(f3_output))
file3.write("\n")

f1_output = int(file1.readline())
f2_output = int(file2.readline())
f3_output = f1_output + f2_output
file3.write(str(f3_output))
file3.write("\n")

f1_output = int(file1.readline())
f2_output = int(file2.readline())
f3_output = f1_output + f2_output
file3.write(str(f3_output))
file3.write("\n")

#Closing Files
file1.close()
file2.close()
file3.close()